mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://www.yycccloud.cn:3306/clipboard?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: